spring.application.name=nutrinest-backend

# Yeh URL bilkul sahi hai, bas ensure karein ki ye saare variables aapke backend service me added hon
spring.datasource.url=jdbc:mysql://${MYSQLHOST}:${MYSQLPORT}/${MYSQLDATABASE}?allowPublicKeyRetrieval=true&useSSL=false

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Railway standard variables
spring.datasource.username=${MYSQLUSER}
spring.datasource.password=${MYSQLPASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# FIXED: Modern MySQL ke liye dialect update kiya hai (Ya is line ko delete bhi kar sakte hain)
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect